exclude: ^node_modules/
repos:
- repo: https://github.com/oxipng/oxipng
  rev: v9.1.5
  hooks:
    - id: oxipng
      name: run oxipng
      description: check PNG files with oxipng
      args: ['--fix', '-o', '4', '--strip', 'safe', '--alpha']
      # types: [image]
      # files: \.png$
