exclude: ^node_modules/
repos:
- repo: local
  hooks:
    - id: biome-check
      # Install biome from https://biomejs.dev/guides/manual-installation/
      # Avoid using NPM to install it until #359 is resolved
      name: biome JS check
      entry: biome check --write --error-on-warnings --files-ignore-unknown=true --no-errors-on-unmatched --colors=off
      language: system
      types: [javascript]
      files: ^atr/static/js/src/.*\.js$
- repo: https://github.com/oxc-project/mirrors-oxlint
  rev: v1.32.0
  hooks:
    - id: oxlint
      name: oxlint JS linter
      types: [javascript]
      files: ^atr/static/js/src/.*\.js$
      args:
        # These must be in the order deny, warn, allow
        - --deny=correctness
        - --deny=perf
        - --deny=suspicious
        - --deny=pedantic
        - --allow=unicorn/prefer-query-selector
- repo: https://github.com/oxipng/oxipng
  rev: v9.1.5
  hooks:
    - id: oxipng
      name: run oxipng
      description: check PNG files with oxipng
      args: ['--fix', '-o', '4', '--strip', 'safe', '--alpha']
      # types: [image]
      # files: \.png$
- repo: https://github.com/semgrep/semgrep
  rev: v1.145.0
  hooks:
    - id: semgrep
      args:
        - --config=p/ci
        - --config=p/clientside-js
        - --config=p/command-injection
        - --config=p/cwe-top-25
        - --config=p/docker-compose
        - --config=p/dockerfile
        - --config=p/flask
        - --config=p/github-actions
        - --config=p/javascript
        - --config=p/jwt
        - --config=p/owasp-top-ten
        - --config=p/python
        - --config=p/python-command-injection
        - --config=p/secrets
        - --config=p/security-audit
        - --config=p/sql-injection
        - --disable-version-check
        - --error
        - --exclude-rule=generic.html-templates.security.var-in-href.var-in-href
        - --exclude-rule=html.security.plaintext-http-link.plaintext-http-link
        - --exclude-rule=python.flask.security.xss.audit.template-unescaped-with-safe.template-unescaped-with-safe
        - --exclude-rule=python.lang.security.audit.dangerous-annotations-usage.dangerous-annotations-usage
        - --exclude-rule=python.lang.security.audit.dangerous-asyncio-create-exec-audit.dangerous-asyncio-create-exec-audit
        - --exclude-rule=python.lang.security.audit.dangerous-subprocess-use-audit.dangerous-subprocess-use-audit
        - --exclude-rule=python.lang.security.use-defused-xml-parse.use-defused-xml-parse
        - --exclude-rule=python.lang.security.use-defused-xml.use-defused-xml
        - --exclude=migrations/versions/0027_2025.09.08_69e565eb.py
        - --metrics=off
        - --quiet
      pass_filenames: false
